<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html dir="{S_CONTENT_DIRECTION}">
<head>
<meta http-equiv="Content-Type" content="text/html; charset={S_CONTENT_ENCODING}">
<meta http-equiv="Content-Style-Type" content="text/css">
<title>Bienvenue sur Simtrain-fr.org</title>

<script language="JavaScript">
<!--

ie4 = ((navigator.appName == "Microsoft Internet Explorer") && (parseInt(navigator.appVersion) >= 4 )) 
ns4 = ((navigator.appName == "Netscape") && (parseInt(navigator.appVersion) >= 4 )) 

if (ns4) { 
layerRef="document.layers"; 
styleRef=""; 
} else { 
layerRef="document.all"; 
styleRef=".style"; 
} 

function afficheCalque(calque) 
{ 
eval(layerRef + '["' + calque +'"]' + styleRef + '.visibility = "visible"'); 
} 

function cacheCalque(calque) 
{ 
eval(layerRef + '["' + calque +'"]' + styleRef + '.visibility = "hidden"'); 
} 
//-->
</script>
<link rel="stylesheet" href="simteoz.css">
</head>

<body bgcolor="#CCCCCC" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<!--           Calques                 -->
<div id="div_discussion" style="position:absolute; left:2.5%; top:157px; width:19%; background-color: #1C2D57; visibility:hidden"
 onmouseover="afficheCalque('div_discussion')" onmouseout="cacheCalque('div_discussion')"> 
  <p class="text_blanc"><a href="http:\\www.simtrain-fr.net" class="text_blanc">Forum</a><br>
    <a href="http://www.simtrain-fr.org/livredor/index.php3" class="text_blanc">Livre 
    d'Or</a></p>
</div>

<div id="div_matos" style="position:absolute; left:21.5%; top:157px; width:19%; background-color: #2C40B8; visibility:hidden"
 onmouseover="afficheCalque('div_matos')" onmouseout="cacheCalque('div_matos')"> 
  <p class="text_blanc"><a href="http://membres.lycos.fr/gigi6930/" class="text_blanc">Les 
    compositions</a><br>
    <a href="http://www.simtrain-fr.org/materiel/locelec/sncf/index.htm" class="text_blanc">Locomotives 
    électriques</a><br>
    <a href="http://www.simtrain-fr.org/materiel/locdies/sncf/index.htm" class="text_blanc">Locomotives 
    diesels</a><br>
    <a href="http://www.simtrain-fr.org/materiel/locvap/sncf/index.htm" class="text_blanc">Locomotives 
    à vapeur</a><br>
    <a href="http://www.simtrain-fr.org/materiel/automel/sncf/index.htm" class="text_blanc">Automotrices</a><br>
    <a href="http://www.simtrain-fr.org/materiel/automdie/sncf/index.htm" class="text_blanc">Automoteurs</a><br>
    <a href="http://www.simtrain-fr.org/materiel/voiture/sncf/index.htm" class="text_blanc">Voitures</a><br>
    <a href="http://www.simtrain-fr.org/materiel/wagon/sncf/index.htm" class="text_blanc">Wagons</a></p>
</div>

<div id="div_voies" style="position:absolute; left:40.5%; top:157px; width:19%; background-color: #4A9CE9; visibility:hidden"
 onmouseover="afficheCalque('div_voies')" onmouseout="cacheCalque('div_voies')"> 
  <p class="text_blanc"><a href="http://perso.wanadoo.fr/simtrain/voie.htm" class="text_blanc">Quelques 
    Voies</a><br>
    <a href="http://www.simtrain-fr.org/lignes_francaises/lignes_fr.htm" class="text_blanc">Les 
    Lignes Françaises</a><br>
    <a href="http://traisimobjet.net/" class="text_blanc">Les objets</a></p>
</div>

<div id="div_cab" style="position:absolute; left:59.5%; top:157px; width:19%; background-color: #32B0F1; visibility:hidden"
 onmouseover="afficheCalque('div_cab')" onmouseout="cacheCalque('div_cab')"> 
  <p class="text_blanc"><a href="http://www.simtrain-fr.org/cabines/cabfr.html" class="text_blanc">Les 
    cabines françaises</a><br>
    <a href="http://www.simtrain-fr.org/cabines/cabeurop.html" class="text_blanc">Les 
    cabines Européennes</a><br>
    <a href="http://www.simtrain-fr.org/cabines/cabmond.html" class="text_blanc">Les 
    cabines du monde</a></p>
</div>

<div id="div_divers" style="position:absolute; left:78.5%; top:157px; width:19%; background-color: #35C6B5; visibility:hidden"
 onmouseover="afficheCalque('div_divers')" onmouseout="cacheCalque('div_divers')"> 
  <p class="text_blanc"><a href="http://www.simtrain-fr.org/liens/lien.html" class="text_blanc">Les 
    liens importants</a><br>
<!--L'équipe<br>
Support technique<br>-->
Tutoriaux<br>
    <a href="http://www.simtrain-fr.org/bve/index.htm" class="text_blanc">Le simulateur 
    BVE</a></p>
</div>
<table width="95%" border="0" cellspacing="0" cellpadding="00" align="center">
  <tr> 
    <td colspan="5" bgcolor="#A8ABB0" height="15"></td>
  </tr>
  <tr height="20"> 
    <td bgcolor="#031940" class="text_blanc">&nbsp;</td>
    <td bgcolor="#002C94" class="text_blanc">&nbsp;</td>
    <td bgcolor="#348AD5" class="text_blanc">&nbsp;</td>
    <td bgcolor="#01A0E1" class="text_blanc">&nbsp;</td>
    <td bgcolor="#12B3A3" class="text_blanc">&nbsp;</td>
  </tr>
  <tr height="74"> 
    <td colspan="5"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="00">
        <tr> 
          <td width="180"><img src="1.jpg" width="180" height="74"></td>
          <td bgcolor="#348AD5" valign="bottom"> 
            <div align="center"><img src="simtrain-fr.gif" width="300" height="59"></div>
          </td>
          <td width="180"><img src="3.jpg" width="180" height="74"></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr height="29"> 
    <td width="20%" class="cell_turbo">&nbsp; </td>
    <td width="20%" class="cell_midi">&nbsp;</td>
    <td width="20%" class="cell_xter">&nbsp;</td>
    <td width="20%" class="cell_duplex">&nbsp;</td>
    <td width="20%" class="cell_141">&nbsp; </td>
  </tr>
  <tr height="20"> 
    <td bgcolor="#031940" width="20%" onmouseover="afficheCalque('div_discussion')" onmouseout="cacheCalque('div_discussion')" class="text_blanc"> 
      Discussion</td>
    <td bgcolor="#002C94" width="20%" onmouseover="afficheCalque('div_matos')" onmouseout="cacheCalque('div_matos')" class="text_blanc">
	  Mat&eacute;riel roulant</td>
    <td bgcolor="#348AD5" width="20%" onmouseover="afficheCalque('div_voies')" onmouseout="cacheCalque('div_voies')" class="text_blanc">
	  Les voies</td>
    <td bgcolor="#01A0E1" width="20%" onmouseover="afficheCalque('div_cab')" onmouseout="cacheCalque('div_cab')" class="text_blanc">
	  Les cabines </td>
    <td bgcolor="#12B3A3" width="20%" onmouseover="afficheCalque('div_divers')" onmouseout="cacheCalque('div_divers')" class="text_blanc">
	  Divers </td>
  </tr>
  <tr> 
    <td colspan="5" bgcolor="#A8ABB0" height="15"></td>
  </tr>
</table>
<br>
<a name="top"></a>

<table width="95%" cellspacing="10" cellpadding="10" border="0" align="center" bgcolor="#EEEEEE"> 
<tr><td> 